name: Use Magic Nix Cache without the requisite permissions.
on:
  pull_request:
  workflow_dispatch:
  push:
jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.1.1
      - uses: DeterminateSystems/nix-installer-action@main
        with:
          flakehub: true
      - uses: DeterminateSystems/magic-nix-cache-action@flakehub
      - run: |
            nix build "https://flakehub.com/f/DeterminateSystems/fh/0.1.9.tar.gz"
